spring:
  application:
    name: ez4webcast
  redis:
    database: 0
    host: ccwserver
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 1
        max-wait: -1
    timeout: 10000
  datasource:
    url: jdbc:mysql://localhost:3306/ez4webcast?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc123lzf
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 600
  address: 127.0.0.1

logging:
  level: info
