spring:
  application:
    name: ez4webcast
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 1
        max-wait: -1
    timeout: 10000
  datasource:
    url: jdbc:mysql://192.168.142.1:3306/ez4webcast?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc123lzf
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 8MB
  session:
    timeout: 36400

server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 600
  address: 0.0.0.0
logging:
  level.root: info
